## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [22]:
import numpy as np

n = int(input())
A = np.arange(n, 0, -1)
print (A)

19
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [78]:
import numpy as np

n = int(input())
M = np.diag(np.arange(n, 0, -1))
print (M)

s = np.diag(M).sum()
print ('The sum of the diagonal values =', s)

7
[[7 0 0 0 0 0 0]
 [0 6 0 0 0 0 0]
 [0 0 5 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 0 2 0]
 [0 0 0 0 0 0 1]]
The sum of the diagonal values = 28


## Задание 3
Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [76]:
import numpy as np
from numpy import linalg

M1 = np.array(([4, 2, 1], [1, 3, 0], [0, 5, 4]))
M2 = np.array ([4, 12, -3])
sol = np.linalg.solve(M1, M2)
print ('The solution of the linear equation: x = %.3f, y = %.3f, z = %.3f' % (sol[0], sol[1], sol[2]))




The solution of the linear equation: x = 0.467, y = 3.844, z = -5.556


## Задание 4
Вам подаются на вход два вектора a и b в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy.

In [68]:
import numpy as np

a = np.random.rand(3)
b = np.random.rand(3)
scalar_prod = np.inner(a,b)

print (a, b, 'Scalar product = %.3f'% (scalar_prod), sep ='\n')


[0.61477725 0.62581901 0.56609715]
[0.01614806 0.82146518 0.81838518]
Scalar product = 0.987
